FileSortAndRename/Models/FileItem.cs
namespace FileSortAndRename.Models
{
    public class FileItem
    {
        public string Name { get; set; }
        public long Size { get; set; }
        public string Path { get; set; }
    }
}

FileSortAndRename/Controllers/BaseController.cs
using System.Web.Mvc;
using FileSortAndRename.Helpers;

namespace FileSortAndRename.Controllers
{
    public class BaseController : Controller
    {
        private readonly Flash _flash;

        protected Flash Flash
        {
            get { return _flash; }
        }

        protected BaseController()
        {
            _flash = new Flash(TempData);
        }
    }
}

FileSortAndRename/Controllers/FileUploadController.cs
using System;
using System.IO;
using System.Web.Mvc;

namespace FileSortAndRename.Controllers
{
    public class FileUploadController : BaseController
    {
        //
        // GET: /FilesUpload/

        public ActionResult Index()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public JsonResult UploadSizeReducedFiles()
        {
            string fileName = null;
            string uploadedFilePath = null;

            try
            {
                fileName = Request.Headers["X-File-Name"];

                var directoryPath = Server.MapPath("~/Uploads/");

                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }

                var stream = new StreamReader(Request.InputStream);
                var image = stream.ReadToEnd();

                image = image.Substring("image=data:image/jpeg;base64,".Length);
                var buffer = Convert.FromBase64String(image);

                uploadedFilePath = string.Format("{0}{1}", directoryPath, fileName);

                System.IO.File.WriteAllBytes(uploadedFilePath, buffer);

                return Json(fileName + " completed", JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                if (System.IO.File.Exists(uploadedFilePath))
                {
                    if (uploadedFilePath != null) System.IO.File.Delete(uploadedFilePath);
                }

                Response.StatusCode = 500;
                return Json(fileName + " fail", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

FileSortAndRename/Controllers/FilesSortController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using FileSortAndRename.Helpers;
using FileSortAndRename.Models;

namespace FileSortAndRename.Controllers
{
    public class FilesSortController : BaseController
    {
        //
        // GET: /FilesSort/

        public ActionResult Index()
        {
            return View(BuildFileList());
        }

        public ActionResult GetFilesList()
        {
            return Json(BuildFileList(), JsonRequestBehavior.AllowGet);
        }

        private IList<FileItem> BuildFileList()
        {
            var fileList = new List<FileItem>();

            var files = Directory.GetFiles(Server.MapPath("~/Uploads"));

            foreach (var file in files.ToList().OrderBy(x => x))
            {
                var fileInfo = new FileInfo(file);

                var fileItem = new FileItem
                {
                    Name = Path.GetFileName(file),
                    Size = fileInfo.Length,
                    Path = ("Uploads/") + Path.GetFileName(file) + "?w=75&h=75&mode=max"
                };

                fileList.Add(fileItem);
            }
            return fileList;
        }

        public ActionResult SaveFiles(string filesList)
        {
            if(string.IsNullOrEmpty(filesList)) return new EmptyResult();
            var orderIndex = 1;
            var files = filesList.Split('|').ToList();

            try
            {
                foreach (var fileName in files)
                {
                    var sourceFilePath = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                    if (System.IO.File.Exists(sourceFilePath))
                    {
                        // Create the target file path
                        var destFilePath = Path.Combine(Server.MapPath("~/Uploads"), string.Format("{0}_{1}", orderIndex.ToString().PadLeft(3, '0'), GetFileNameWithoutOrderIndex(fileName)));

                        if (!sourceFilePath.Equals(destFilePath, StringComparison.OrdinalIgnoreCase))
                        {
                            // Copy the new ordered file
                            System.IO.File.Copy(sourceFilePath, destFilePath);
                            System.IO.File.Delete(sourceFilePath);
                        }
                    }
                    orderIndex++;
                }

            }
            catch (Exception ex)
            {
                //Flash[FlashKey.Error] = ex.Message;
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            //Flash[FlashKey.Notice] = "Files saved successfuly.";
            return Json(BuildFileList(), JsonRequestBehavior.AllowGet);
        }

        private string GetFileNameWithoutOrderIndex(string fileName)
        {
            // If a file was previously indexed, then it should be in a format: 001_SomeName.ext.
            // Then, extract only the file name after the underscore char (_)
            return fileName.Substring(3, 1).Equals("_", StringComparison.InvariantCultureIgnoreCase) 
                ? fileName.Substring(4) 
                : fileName;
        }

        private void DeleteOldFiles(string[] oldOrderedFiles, string fileName)
        {
            var oldFiles = oldOrderedFiles.Where(x => x.Contains(fileName)).ToList();

            foreach (var oldFile in oldFiles)
            {
                if (System.IO.File.Exists(oldFile))
                {
                    System.IO.File.Delete(oldFile);
                }
            }
        }
    }
}

FileSortAndRename/Views/FileUpload/Index.cshtml
@{
    ViewBag.Title = "File Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<p>
    <span>First step: </span>
    <input type="button" value="Choose images" class="btn-large btn-primary" onclick="javascript: document.getElementById('filesToUpload').click();">
    <input type="file" accept="image/*" multiple name="filesToUpload[]" id="filesToUpload" style='visibility: hidden;'
        onchange="fileSelected();" />
</p>
<div style="clear: both;">
    <ul class="inline alert-info" id="uploadfilelist">
    </ul>
</div>

<p style="margin-top: 15px;">
    <input type="button" onclick="uploadFiles();" value="Upload (max 500 files)" class="btn-large btn-success" />
</p>

<script type="text/javascript">
    var UPLOAD_URL = '@Url.Action("UploadSizeReducedFiles", "FileUpload")';
    var FILES_SORT_URL = '@Url.Action("Index", "FilesSort")';
</script>

FileSortAndRename/Views/FilesSort/FileList.cshtml
@using FileSortAndRename.Helpers
@model IList<FileSortAndRename.Models.FileItem>


<style>
    #sortable {
        list-style-type: none;
        margin: 0;
        padding: 0;
        width: 60%;
    }

        #sortable li {
            margin: 0 3px 3px 3px;
            padding: 0.1em;
            padding-left: 1.5em;
            font-size: 1.0em;
            height: 75px;
            border: dotted 1px #a4b1e3;
        }

            #sortable li span {
                position: absolute;
                margin-left: -1.3em;
            }

    #productImagePopup {
        border: 2px solid black;
    }


    li {
        background-color: Azure;
        border-bottom: 1px dotted Gray;
    }

        li.selected {
            background-color: #dae719;
        }
</style>

<strong class="error">{{ error }}</strong>
<strong ng-show="loading">loading...</strong>

<ul id="sortable">
    <li ng-repeat="fileItem in fileList" id="{{ fileItem.Name }}"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
        <img ng-src="{{ fileItem.Path }}" class="productImage" />&nbsp;&nbsp;
        {{ fileItem.Name }}
    </li>
</ul>
@*style="max-width: 75px; max-height: 75px;"*@

@*<pre ng-bind="fileList|json"></pre>*@


@*<ul id="sortable">
    @foreach (var fileItem in Model.ToList().OrderBy(x => x.Name))
    {
        <li class="ui-state-default" id="@fileItem.Name"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
            @Html.Raw(@Html.Image(fileItem.Name, fileItem.Path, new { width = 40, height = 40 }))&nbsp;&nbsp;
            @fileItem.Name (@(fileItem.Size / 1000) KB)
        </li>
    }

</ul>*@

<script>
    $(function () {
        $("#sortable").sortable();
        //$("#sortable").disableSelection();

        $("ul").on('click', 'li', function (e) {
            if (e.ctrlKey || e.metaKey) {
                $(this).toggleClass("selected");
            } else {
                $(this).addClass("selected").siblings().removeClass('selected');
            }
        }).sortable({
            connectWith: "ul",
            delay: 150, //Needed to prevent accidental drag when trying to select
            revert: 0,
            helper: function (e, item) {
                //Basically, if you grab an unhighlighted item to drag, it will deselect (unhighlight) everything else
                if (!item.hasClass('selected')) {
                    item.addClass('selected').siblings().removeClass('selected');
                }

                //////////////////////////////////////////////////////////////////////
                //HERE'S HOW TO PASS THE SELECTED ITEMS TO THE `stop()` FUNCTION:

                //Clone the selected items into an array
                var elements = item.parent().children('.selected').clone();

                //Add a property to `item` called 'multidrag` that contains the 
                //  selected items, then remove the selected items from the source list
                item.data('multidrag', elements).siblings('.selected').remove();

                //Now the selected items exist in memory, attached to the `item`,
                //  so we can access them later when we get to the `stop()` callback

                //Create the helper
                var helper = $('<li/>');
                return helper.append(elements);
            },
            stop: function (e, ui) {
                //Now we access those items that we stored in `item`s data!
                var elements = ui.item.data('multidrag');

                //`elements` now contains the originally selected items from the source list (the dragged items)!!

                //Finally I insert the selected items after the `item`, then remove the `item`, since 
                //  item is a duplicate of one of the selected items.
                ui.item.after(elements).remove();
            }

        });

    });
  
</script>

FileSortAndRename/Views/FilesSort/Index.cshtml
@{
    ViewBag.Title = "SORT";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IList<FileSortAndRename.Models.FileItem>
<script src="~/Scripts/ng-controllers/file-list-controller.js"></script>

<h2>Sort Files</h2>

<div ng-controller="FileListController">

    <div ng-show="success" id="savesuccess" class="flash-box notice">Files saved successfuly.</div>

    @Html.Partial("FileList")

    <div id="nofilesfound" ng-show="fileList.length <= 0" class="flash-box warning">
        No files found
    </div>

    <div ng-show="fileList.length > 0">
        <input id="btnSaveFiles" type="button" value="Save Files" class="btn-large btn-success" ng-click="save()" href="javascript:;" />
    </div>

</div>

FileSortAndRename/Views/Shared/Flash.cshtml
@using FileSortAndRename.Helpers
@{
    var cssClass = "";
    var message = "";
    var renderMessage = false;
    foreach (FlashKey key in Enum.GetValues(typeof(FlashKey)))
    {
        var data = TempData[string.Format("Flash_{0}", key)];
        if (data == null) { continue; }

        message = data.ToString();
        cssClass = key.ToString().ToLower();
        renderMessage = true;
    }    
}
@if (renderMessage)
{
    <div id="flash-box" class="@cssClass">@Html.Raw(message)</div>
}
else
{
    <div id="flash-box" class="@cssClass" style="display:none;">
    </div>
}

FileSortAndRename/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en" ng-app>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/sunny/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script src="~/Scripts/Angular/angular.min.js"></script>
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/file-upload.js"></script>
    <meta name="viewport" content="width=device-width">
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("Resorte - File Sort and Rename", "Index", "FileUpload")</p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Upload Images", "Index", "FileUpload")</li>
                        <li>@Html.ActionLink("Sort Images", "Index", "FilesSort")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - Resorte - File Sort &amp; Rename</p>
            </div>
            <div class="float-right">
                <ul id="social">
                    <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                    <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>
</html>

FileSortAndRename/Views/Shared/_Layout.cshtml.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-2.0.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.3.min.js")" type="text/javascript"></script>
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/bootstrap")
    <meta name="viewport" content="width=device-width">
</head>
<body>
    <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here.", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
    <div id="body">
        <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
    </div>
    <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Resorte - File Sort &amp; Rename</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
</body>
</html>